# Generated by Django 4.2.11 on 2026-07-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_tokenrevocado'),
        ('tutorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringparticipation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='tutorias.tutoringsession'),
        ),
        migrations.AlterField(
            model_name='tutoringparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='usuarios.usuario'),
        ),
    ]
