# Generated by Django 4.2.11 on 2026-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoravailability',
            name='max_capacity',
            field=models.IntegerField(default=5),
        ),
    ]
