# Generated by Django 4.2.11 on 2026-07-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_tokenrevocado'),
        ('tutorias', '0002_alter_tutoringparticipation_session_and_more'),
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondido', 'Respondido')], default='pendiente', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cuestionarios.questionnaire')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_assignments', to='tutorias.tutoringsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_questionnaires', to='usuarios.usuario')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'asignacion_cuestionario',
                'unique_together': {('questionnaire', 'student', 'session')},
            },
        ),
    ]
