# Generated by Django 4.2.11 on 2026-07-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_tokenrevocado'),
        ('cuestionarios', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresult',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_results_as_tutor', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='questionnaireresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_results', to='usuarios.usuario'),
        ),
    ]
