# Generated by Django 6.0.4 on 2026-06-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'rol_permiso',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='usuario_correo_94dccf_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['activo'], name='usuario_activo_2eb730_idx'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permiso'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='usuarios.rol'),
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('rol', 'permiso')},
        ),
    ]
